/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author ranie
 */
public class Cadastro2 extends javax.swing.JFrame {

    Contas c1;
    ContaPoupanca conta2 = new ContaPoupanca();
    
    /**
     * Creates new form Cadastro1
     * @param con1
     */
    public Cadastro2(Contas con1) {
        this.c1 = con1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContaPoupanca = new javax.swing.JLabel();
        lblNomeTitularContaPoupanca = new javax.swing.JLabel();
        lblNumeroContaContaPoupanca = new javax.swing.JLabel();
        lblSaldoInicialContaPoupanca = new javax.swing.JLabel();
        btnContinuarParaContaEspecial = new javax.swing.JButton();
        lblInformacoesNecessariasContaPoupanca = new javax.swing.JLabel();
        lblTaxaReajusteContaPoupanca = new javax.swing.JLabel();
        textFieldNomeTitularContaPoupanca = new javax.swing.JTextField();
        textFieldNumeroContaContaPoupanca = new javax.swing.JTextField();
        textFieldSaldoInicialContaPoupanca = new javax.swing.JTextField();
        textFieldTaxaReajusteContaPoupanca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblContaPoupanca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContaPoupanca.setText("Cadastro - Conta-poupança");

        lblNomeTitularContaPoupanca.setText("Nome do titular:");

        lblNumeroContaContaPoupanca.setText("Número da conta:");

        lblSaldoInicialContaPoupanca.setText("Saldo inicial:");

        btnContinuarParaContaEspecial.setText("Continuar para o próximo cadastro (Conta-especial)");
        btnContinuarParaContaEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarParaContaEspecialActionPerformed(evt);
            }
        });

        lblInformacoesNecessariasContaPoupanca.setText("Informações necessárias:");

        lblTaxaReajusteContaPoupanca.setText("Taxa de reajuste:");

        textFieldNomeTitularContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeTitularContaPoupancaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoInicialContaPoupanca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSaldoInicialContaPoupanca))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeTitularContaPoupanca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNomeTitularContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroContaContaPoupanca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNumeroContaContaPoupanca))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(lblContaPoupanca)
                            .addComponent(btnContinuarParaContaEspecial)))
                    .addComponent(lblInformacoesNecessariasContaPoupanca)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTaxaReajusteContaPoupanca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldTaxaReajusteContaPoupanca)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblContaPoupanca)
                .addGap(4, 4, 4)
                .addComponent(lblInformacoesNecessariasContaPoupanca)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTitularContaPoupanca)
                    .addComponent(textFieldNomeTitularContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroContaContaPoupanca)
                    .addComponent(textFieldNumeroContaContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicialContaPoupanca)
                    .addComponent(textFieldSaldoInicialContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaxaReajusteContaPoupanca)
                    .addComponent(textFieldTaxaReajusteContaPoupanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnContinuarParaContaEspecial)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarParaContaEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarParaContaEspecialActionPerformed
        // TODO add your handling code here:
        
        //Set do Nome do Titular
        if(!textFieldNomeTitularContaPoupanca.getText().equals("")){
            conta2.setNome(textFieldNomeTitularContaPoupanca.getText());
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o nome do titular da conta-poupança!");
            return;
        }
        
        //Set do Número da Conta
        if(!textFieldNumeroContaContaPoupanca.getText().equals("")){
            conta2.setNumero(Integer.parseInt(textFieldNumeroContaContaPoupanca.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o número da conta-poupança!");
            return;
        }
        
        //Set do Saldo Inicial da Conta
        if(!textFieldSaldoInicialContaPoupanca.getText().equals("")){
            conta2.setSaldo(Double.parseDouble(textFieldSaldoInicialContaPoupanca.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor do saldo inicial da conta-poupança!");
            return;
        }
        
        //Set da taxa de reajuste
        if(!textFieldTaxaReajusteContaPoupanca.getText().equals("")){
            conta2.setTaxa(Double.parseDouble(textFieldTaxaReajusteContaPoupanca.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor da taxa de reajuste da conta-poupança!");
            return;
        }
        
        //teste para verificar se os valores digitados pelo usuário estavam sendo salvos
        System.out.println("Conta2 - Nome do Titular: "+conta2.getNome());
        System.out.println("Conta2 - Número da Conta: "+conta2.getNumero());
        System.out.println("Conta2 - Saldo Inicial: "+conta2.getSaldo());
        System.out.println("Conta2 - Taxa de reajuste: "+conta2.getTaxa());
        
        
        this.setVisible(false); //Fechar a janela aberta para exibir a seguinte
        new Cadastro3(c1, conta2).setVisible(true);
    }//GEN-LAST:event_btnContinuarParaContaEspecialActionPerformed

    private void textFieldNomeTitularContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeTitularContaPoupancaActionPerformed
        // TODO add your handling code here:
        String nomeTitularContaPoupanca;
    }//GEN-LAST:event_textFieldNomeTitularContaPoupancaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarParaContaEspecial;
    private javax.swing.JLabel lblContaPoupanca;
    private javax.swing.JLabel lblInformacoesNecessariasContaPoupanca;
    private javax.swing.JLabel lblNomeTitularContaPoupanca;
    private javax.swing.JLabel lblNumeroContaContaPoupanca;
    private javax.swing.JLabel lblSaldoInicialContaPoupanca;
    private javax.swing.JLabel lblTaxaReajusteContaPoupanca;
    private javax.swing.JTextField textFieldNomeTitularContaPoupanca;
    private javax.swing.JTextField textFieldNumeroContaContaPoupanca;
    private javax.swing.JTextField textFieldSaldoInicialContaPoupanca;
    private javax.swing.JTextField textFieldTaxaReajusteContaPoupanca;
    // End of variables declaration//GEN-END:variables
}
