/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author ranie
 */
public class Cadastro3 extends javax.swing.JFrame {

    Contas cont1;
    ContaPoupanca cont2;
    ContaEspecial conta3 = new ContaEspecial();
    /**
     * Creates new form Cadastro1
     * @param c1
     * @param conta2
     */
    public Cadastro3(Contas c1, ContaPoupanca conta2) {
        this.cont1 = c1;
        this.cont2 = conta2;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContaEspecial = new javax.swing.JLabel();
        lblNomeTitularContaEspecial = new javax.swing.JLabel();
        lblNumeroContaContaEspecial = new javax.swing.JLabel();
        lblSaldoInicialContaEspecial = new javax.swing.JLabel();
        btnFinalizarCadastrosParaFaseDeOperacoes = new javax.swing.JButton();
        lblInformacoesNecessariasContaEspecial = new javax.swing.JLabel();
        lblLimiteContaEspecial = new javax.swing.JLabel();
        lblMultaContaEspecial = new javax.swing.JLabel();
        textFieldNomeTitularContaEspecial = new javax.swing.JTextField();
        textFieldNumeroContaContaEspecial = new javax.swing.JTextField();
        textFieldSaldoInicialContaEspecial = new javax.swing.JTextField();
        textFieldLimiteContaEspecial = new javax.swing.JTextField();
        textFieldMultaContaEspecial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblContaEspecial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContaEspecial.setText("Cadastro - Conta-especial");

        lblNomeTitularContaEspecial.setText("Nome do titular:");

        lblNumeroContaContaEspecial.setText("Número da conta:");

        lblSaldoInicialContaEspecial.setText("Saldo inicial:");

        btnFinalizarCadastrosParaFaseDeOperacoes.setText("Finalizar cadastros (seguir para a Fase de Operações)");
        btnFinalizarCadastrosParaFaseDeOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCadastrosParaFaseDeOperacoesActionPerformed(evt);
            }
        });

        lblInformacoesNecessariasContaEspecial.setText("Informações necessárias:");

        lblLimiteContaEspecial.setText("Limite:");

        lblMultaContaEspecial.setText("Multa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lblContaEspecial))
                    .addComponent(lblInformacoesNecessariasContaEspecial)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoInicialContaEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSaldoInicialContaEspecial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroContaContaEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNumeroContaContaEspecial))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnFinalizarCadastrosParaFaseDeOperacoes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeTitularContaEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNomeTitularContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLimiteContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldLimiteContaEspecial))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMultaContaEspecial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldMultaContaEspecial)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblContaEspecial)
                .addGap(4, 4, 4)
                .addComponent(lblInformacoesNecessariasContaEspecial)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTitularContaEspecial)
                    .addComponent(textFieldNomeTitularContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroContaContaEspecial)
                    .addComponent(textFieldNumeroContaContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicialContaEspecial)
                    .addComponent(textFieldSaldoInicialContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteContaEspecial)
                    .addComponent(textFieldLimiteContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMultaContaEspecial)
                    .addComponent(textFieldMultaContaEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarCadastrosParaFaseDeOperacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarCadastrosParaFaseDeOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCadastrosParaFaseDeOperacoesActionPerformed
        // TODO add your handling code here:
        
        //Set do Nome do Titular da Conta-Especial
        if(!textFieldNomeTitularContaEspecial.getText().equals("")){
            conta3.setNome(textFieldNomeTitularContaEspecial.getText());
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o nome do titular da conta-especial!");
            return;
        }
        
        //Set do Número da Conta-Especial
        if(!textFieldNumeroContaContaEspecial.getText().equals("")){
            conta3.setNumero(Integer.parseInt(textFieldNumeroContaContaEspecial.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o número da conta-especial!");
            return;
        }
        
        //Set do Saldo Inicial da Conta-Especial
        if(!textFieldSaldoInicialContaEspecial.getText().equals("")){
            conta3.setSaldo(Double.parseDouble(textFieldSaldoInicialContaEspecial.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor do saldo inicial da conta-especial!");
            return;
        }
        
        //Set do Limite da Conta-Especial
        if(!textFieldLimiteContaEspecial.getText().equals("")){
            conta3.setLimite(Integer.parseInt(textFieldLimiteContaEspecial.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor do limite da conta-especial!");
            return;
        }
        
        //Set da Multa da Conta-Especial
        if(!textFieldMultaContaEspecial.getText().equals("")){
            conta3.setMulta(Double.parseDouble(textFieldMultaContaEspecial.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor da multa da conta-especial!");
            return;
        }
        
        //teste para verificar se os valores digitados pelo usuário estavam sendo salvos
        System.out.println("Conta3 - Nome do Titular: "+conta3.getNome());
        System.out.println("Conta3 - Número da Conta: "+conta3.getNumero());
        System.out.println("Conta3 - Saldo Inicial: "+conta3.getSaldo());
        System.out.println("Conta3 - Limite: "+conta3.getLimite());
        System.out.println("Conta3 - Multa: "+conta3.getMulta());
        
        
        this.setVisible(false); //Fechar a janela aberta para exibir a seguinte
        new FaseDeOperacoes(cont1, cont2, conta3).setVisible(true); //Chama a tela da fase de operações
    }//GEN-LAST:event_btnFinalizarCadastrosParaFaseDeOperacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarCadastrosParaFaseDeOperacoes;
    private javax.swing.JLabel lblContaEspecial;
    private javax.swing.JLabel lblInformacoesNecessariasContaEspecial;
    private javax.swing.JLabel lblLimiteContaEspecial;
    private javax.swing.JLabel lblMultaContaEspecial;
    private javax.swing.JLabel lblNomeTitularContaEspecial;
    private javax.swing.JLabel lblNumeroContaContaEspecial;
    private javax.swing.JLabel lblSaldoInicialContaEspecial;
    private javax.swing.JTextField textFieldLimiteContaEspecial;
    private javax.swing.JTextField textFieldMultaContaEspecial;
    private javax.swing.JTextField textFieldNomeTitularContaEspecial;
    private javax.swing.JTextField textFieldNumeroContaContaEspecial;
    private javax.swing.JTextField textFieldSaldoInicialContaEspecial;
    // End of variables declaration//GEN-END:variables
}
