/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author ranie
 */
public class Cadastro1 extends javax.swing.JFrame {

    Contas conta1 = new Contas();
    
    /**
     * Creates new form Cadastro1
     */
    public Cadastro1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContaComum = new javax.swing.JLabel();
        lblNomeTitularContaComum = new javax.swing.JLabel();
        lblNumeroContaContaComum = new javax.swing.JLabel();
        lblSaldoInicialContaComum = new javax.swing.JLabel();
        btnContinuarParaContaPoupanca = new javax.swing.JButton();
        lblInformacoesNecessariasContaComum = new javax.swing.JLabel();
        textFieldNomeTitularContaComum = new javax.swing.JTextField();
        textFieldNumeroContaContaComum = new javax.swing.JTextField();
        textFieldSaldoInicialContaComum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblContaComum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContaComum.setText("Cadastro - Conta-comum");

        lblNomeTitularContaComum.setText("Nome do titular:");

        lblNumeroContaContaComum.setText("Número da conta:");

        lblSaldoInicialContaComum.setText("Saldo inicial:");

        btnContinuarParaContaPoupanca.setText("Continuar para o próximo cadastro (Conta-poupança)");
        btnContinuarParaContaPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarParaContaPoupancaActionPerformed(evt);
            }
        });

        lblInformacoesNecessariasContaComum.setText("Informações necessárias:");

        textFieldNomeTitularContaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNomeTitularContaComumActionPerformed(evt);
            }
        });

        textFieldNumeroContaContaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroContaContaComumActionPerformed(evt);
            }
        });

        textFieldSaldoInicialContaComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSaldoInicialContaComumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoInicialContaComum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSaldoInicialContaComum))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeTitularContaComum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNomeTitularContaComum, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumeroContaContaComum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNumeroContaContaComum))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnContinuarParaContaPoupanca)
                            .addComponent(lblContaComum)))
                    .addComponent(lblInformacoesNecessariasContaComum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblContaComum)
                .addGap(4, 4, 4)
                .addComponent(lblInformacoesNecessariasContaComum)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTitularContaComum)
                    .addComponent(textFieldNomeTitularContaComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroContaContaComum)
                    .addComponent(textFieldNumeroContaContaComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoInicialContaComum)
                    .addComponent(textFieldSaldoInicialContaComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnContinuarParaContaPoupanca)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarParaContaPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarParaContaPoupancaActionPerformed
        // TODO add your handling code here:
        //Set do Nome do Titular
        if(!textFieldNomeTitularContaComum.getText().equals("")){
            conta1.setNome(textFieldNomeTitularContaComum.getText());
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o nome do titular da conta-comum!");
            return;
        }
        //Set do Número da Conta
        if(!textFieldNumeroContaContaComum.getText().equals("")){
            conta1.setNumero(Integer.parseInt(textFieldNumeroContaContaComum.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o número da conta-comum!");
            return;
        }
        //Set do Saldo Inicial da Conta
        if(!textFieldSaldoInicialContaComum.getText().equals("")){
            conta1.setSaldo(Double.parseDouble(textFieldSaldoInicialContaComum.getText()));
            
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, insira o valor do saldo inicial da conta-comum!");
            return;
        }
        
        //teste para verificar se os valores digitados pelo usuário estavam sendo salvos
        System.out.println("Conta1 - Nome do Titular: "+conta1.getNome());
        System.out.println("Conta1 - Número da Conta: "+conta1.getNumero());
        System.out.println("Conta1 - Saldo Inicial: "+conta1.getSaldo());
        
        
        this.setVisible(false); //Fechar a janela aberta para exibir a seguinte
        new Cadastro2(conta1).setVisible(true);
        
    }//GEN-LAST:event_btnContinuarParaContaPoupancaActionPerformed

    private void textFieldNomeTitularContaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNomeTitularContaComumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textFieldNomeTitularContaComumActionPerformed

    private void textFieldNumeroContaContaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroContaContaComumActionPerformed
        // TODO add your handling code here:
        //conta1.setNumero(Integer.parseInt(textFieldNumeroContaContaComum.getText()));
    }//GEN-LAST:event_textFieldNumeroContaContaComumActionPerformed

    private void textFieldSaldoInicialContaComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSaldoInicialContaComumActionPerformed
        // TODO add your handling code here:
        //conta1.setSaldo(Double.parseDouble(textFieldSaldoInicialContaComum.getText()));
    }//GEN-LAST:event_textFieldSaldoInicialContaComumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro1().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarParaContaPoupanca;
    private javax.swing.JLabel lblContaComum;
    private javax.swing.JLabel lblInformacoesNecessariasContaComum;
    private javax.swing.JLabel lblNomeTitularContaComum;
    private javax.swing.JLabel lblNumeroContaContaComum;
    private javax.swing.JLabel lblSaldoInicialContaComum;
    private javax.swing.JTextField textFieldNomeTitularContaComum;
    private javax.swing.JTextField textFieldNumeroContaContaComum;
    private javax.swing.JTextField textFieldSaldoInicialContaComum;
    // End of variables declaration//GEN-END:variables

    
    
}
