/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author ranie
 */
public class FaseDeOperacoes extends javax.swing.JFrame {

    Contas acc1;
    ContaPoupanca acc2; 
    ContaEspecial acc3;
    /**
     * Creates new form FaseDeOperacoes
     * @param cont1
     * @param cont2
     * @param conta3
     */
    public FaseDeOperacoes(Contas cont1, ContaPoupanca cont2, ContaEspecial conta3) {
        this.acc1 = cont1;
        this.acc2 = cont2;
        this.acc3 = conta3;
        initComponents();
    }

    private FaseDeOperacoes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /*
    FaseDeOperacoes(Contas cont1, ContaPoupanca cont2, ContaEspecial conta3) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnOperacaoSaque = new javax.swing.JButton();
        btnOperacaoDeposito = new javax.swing.JButton();
        btnOperacaoTransferencia = new javax.swing.JButton();
        btnOperacaoReajustar = new javax.swing.JButton();
        btnOperacaoVerSaldos = new javax.swing.JButton();
        btnSairFaseDeOperacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Selecione a operação desejada");

        btnOperacaoSaque.setText("Saque");
        btnOperacaoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoSaqueActionPerformed(evt);
            }
        });

        btnOperacaoDeposito.setText("Depósito");
        btnOperacaoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoDepositoActionPerformed(evt);
            }
        });

        btnOperacaoTransferencia.setText("Transferência");
        btnOperacaoTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoTransferenciaActionPerformed(evt);
            }
        });

        btnOperacaoReajustar.setText("Reajustar");
        btnOperacaoReajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoReajustarActionPerformed(evt);
            }
        });

        btnOperacaoVerSaldos.setText("Ver saldos");
        btnOperacaoVerSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacaoVerSaldosActionPerformed(evt);
            }
        });

        btnSairFaseDeOperacoes.setText("Sair");
        btnSairFaseDeOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairFaseDeOperacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOperacaoVerSaldos)
                        .addGap(6, 6, 6)
                        .addComponent(btnSairFaseDeOperacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOperacaoTransferencia)
                        .addGap(6, 6, 6)
                        .addComponent(btnOperacaoReajustar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOperacaoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnOperacaoDeposito)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperacaoSaque)
                    .addComponent(btnOperacaoDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperacaoTransferencia)
                    .addComponent(btnOperacaoReajustar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOperacaoVerSaldos)
                    .addComponent(btnSairFaseDeOperacoes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairFaseDeOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairFaseDeOperacoesActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairFaseDeOperacoesActionPerformed

    private void btnOperacaoTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoTransferenciaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha a tela de operações
        new TelaTransferencia(acc1, acc2, acc3).setVisible(true);
        
    }//GEN-LAST:event_btnOperacaoTransferenciaActionPerformed

    private void btnOperacaoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoSaqueActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha a tela de operações
        new TelaSaque(acc1, acc2, acc3).setVisible(true);
        
    }//GEN-LAST:event_btnOperacaoSaqueActionPerformed

    private void btnOperacaoVerSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoVerSaldosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha a tela de operações
        new TelaVerSaldos(acc1, acc2, acc3).setVisible(true);
    }//GEN-LAST:event_btnOperacaoVerSaldosActionPerformed

    private void btnOperacaoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoDepositoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); //fecha a tela de operações
        new TelaDeposito(acc1, acc2, acc3).setVisible(true);
    }//GEN-LAST:event_btnOperacaoDepositoActionPerformed

    private void btnOperacaoReajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacaoReajustarActionPerformed
        // TODO add your handling code here:
        double taxa = 0;
        int numeroConta;
        
        numeroConta = Integer.parseInt(JOptionPane.showInputDialog(null, "Por favor, digite o número da conta poupança a ser reajustada: ", "Operação: Reajuste", JOptionPane.QUESTION_MESSAGE));
        
        try{
            taxa = Double.parseDouble(JOptionPane.showInputDialog(null, "Por favor, digite a taxa de reajuste (ex: 7%): ", "Operação: Reajuste", JOptionPane.QUESTION_MESSAGE));
            
            if(numeroConta == acc2.getNumero())
            {
                acc2.reajustar(taxa);
                JOptionPane.showMessageDialog(null,"Operação de ajuste realizada com sucesso.","Operação: Reajuste",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Erro: Número da conta-poupança informado é inválido.","Operação: Reajuste",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(java.lang.NumberFormatException e){
            if(numeroConta == acc2.getNumero())
            {
                acc2.reajustar();//usuário não digitou a taxa, caiu na taxa padrão de 0.1 = 10%
                JOptionPane.showMessageDialog(null,"Operação de ajuste realizada com sucesso.","Operação: Reajuste",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null,"Erro: Número da conta-poupança informado é inválido.","Operação: Reajuste",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        System.out.println("Taxa de reajuste: "+taxa);
    }//GEN-LAST:event_btnOperacaoReajustarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaseDeOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaseDeOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaseDeOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaseDeOperacoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaseDeOperacoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOperacaoDeposito;
    private javax.swing.JButton btnOperacaoReajustar;
    private javax.swing.JButton btnOperacaoSaque;
    private javax.swing.JButton btnOperacaoTransferencia;
    private javax.swing.JButton btnOperacaoVerSaldos;
    private javax.swing.JButton btnSairFaseDeOperacoes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
